// Generated by the protocol buffer compiler.  DO NOT EDIT!

package noop.model.proto;

public final class NoopAst {
  private NoopAst() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Expr extends
      com.google.protobuf.GeneratedMessage {
    // Use Expr.newBuilder() to construct.
    private Expr() {}
    
    private static final Expr defaultInstance = new Expr();
    public static Expr getDefaultInstance() {
      return defaultInstance;
    }
    
    public Expr getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noop.model.proto.NoopAst.internal_static_Expr_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noop.model.proto.NoopAst.internal_static_Expr_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      BOOLEAN_LITERAL(0, 1),
      STRING_LITERAL(1, 2),
      INT_LITERAL(2, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return BOOLEAN_LITERAL;
          case 2: return STRING_LITERAL;
          case 3: return INT_LITERAL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return noop.model.proto.NoopAst.Expr.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        BOOLEAN_LITERAL, STRING_LITERAL, INT_LITERAL, 
      };
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        noop.model.proto.NoopAst.getDescriptor();
      }
    }
    
    // required .Expr.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private noop.model.proto.NoopAst.Expr.Type type_ = noop.model.proto.NoopAst.Expr.Type.BOOLEAN_LITERAL;
    public boolean hasType() { return hasType; }
    public noop.model.proto.NoopAst.Expr.Type getType() { return type_; }
    
    // optional .BooleanLiteral booleanLiteral = 2;
    public static final int BOOLEANLITERAL_FIELD_NUMBER = 2;
    private boolean hasBooleanLiteral;
    private noop.model.proto.NoopAst.BooleanLiteral booleanLiteral_ = noop.model.proto.NoopAst.BooleanLiteral.getDefaultInstance();
    public boolean hasBooleanLiteral() { return hasBooleanLiteral; }
    public noop.model.proto.NoopAst.BooleanLiteral getBooleanLiteral() { return booleanLiteral_; }
    
    // optional .StringLiteral stringLiteral = 3;
    public static final int STRINGLITERAL_FIELD_NUMBER = 3;
    private boolean hasStringLiteral;
    private noop.model.proto.NoopAst.StringLiteral stringLiteral_ = noop.model.proto.NoopAst.StringLiteral.getDefaultInstance();
    public boolean hasStringLiteral() { return hasStringLiteral; }
    public noop.model.proto.NoopAst.StringLiteral getStringLiteral() { return stringLiteral_; }
    
    // optional .IntLiteral intLiteral = 4;
    public static final int INTLITERAL_FIELD_NUMBER = 4;
    private boolean hasIntLiteral;
    private noop.model.proto.NoopAst.IntLiteral intLiteral_ = noop.model.proto.NoopAst.IntLiteral.getDefaultInstance();
    public boolean hasIntLiteral() { return hasIntLiteral; }
    public noop.model.proto.NoopAst.IntLiteral getIntLiteral() { return intLiteral_; }
    
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (hasBooleanLiteral()) {
        if (!getBooleanLiteral().isInitialized()) return false;
      }
      if (hasStringLiteral()) {
        if (!getStringLiteral().isInitialized()) return false;
      }
      if (hasIntLiteral()) {
        if (!getIntLiteral().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasBooleanLiteral()) {
        output.writeMessage(2, getBooleanLiteral());
      }
      if (hasStringLiteral()) {
        output.writeMessage(3, getStringLiteral());
      }
      if (hasIntLiteral()) {
        output.writeMessage(4, getIntLiteral());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasBooleanLiteral()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBooleanLiteral());
      }
      if (hasStringLiteral()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStringLiteral());
      }
      if (hasIntLiteral()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getIntLiteral());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static noop.model.proto.NoopAst.Expr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.Expr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(noop.model.proto.NoopAst.Expr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private noop.model.proto.NoopAst.Expr result;
      
      // Construct using noop.model.proto.NoopAst.Expr.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new noop.model.proto.NoopAst.Expr();
        return builder;
      }
      
      protected noop.model.proto.NoopAst.Expr internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new noop.model.proto.NoopAst.Expr();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noop.model.proto.NoopAst.Expr.getDescriptor();
      }
      
      public noop.model.proto.NoopAst.Expr getDefaultInstanceForType() {
        return noop.model.proto.NoopAst.Expr.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public noop.model.proto.NoopAst.Expr build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private noop.model.proto.NoopAst.Expr buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public noop.model.proto.NoopAst.Expr buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        noop.model.proto.NoopAst.Expr returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noop.model.proto.NoopAst.Expr) {
          return mergeFrom((noop.model.proto.NoopAst.Expr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(noop.model.proto.NoopAst.Expr other) {
        if (other == noop.model.proto.NoopAst.Expr.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBooleanLiteral()) {
          mergeBooleanLiteral(other.getBooleanLiteral());
        }
        if (other.hasStringLiteral()) {
          mergeStringLiteral(other.getStringLiteral());
        }
        if (other.hasIntLiteral()) {
          mergeIntLiteral(other.getIntLiteral());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              noop.model.proto.NoopAst.Expr.Type value = noop.model.proto.NoopAst.Expr.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              noop.model.proto.NoopAst.BooleanLiteral.Builder subBuilder = noop.model.proto.NoopAst.BooleanLiteral.newBuilder();
              if (hasBooleanLiteral()) {
                subBuilder.mergeFrom(getBooleanLiteral());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBooleanLiteral(subBuilder.buildPartial());
              break;
            }
            case 26: {
              noop.model.proto.NoopAst.StringLiteral.Builder subBuilder = noop.model.proto.NoopAst.StringLiteral.newBuilder();
              if (hasStringLiteral()) {
                subBuilder.mergeFrom(getStringLiteral());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStringLiteral(subBuilder.buildPartial());
              break;
            }
            case 34: {
              noop.model.proto.NoopAst.IntLiteral.Builder subBuilder = noop.model.proto.NoopAst.IntLiteral.newBuilder();
              if (hasIntLiteral()) {
                subBuilder.mergeFrom(getIntLiteral());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIntLiteral(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .Expr.Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public noop.model.proto.NoopAst.Expr.Type getType() {
        return result.getType();
      }
      public Builder setType(noop.model.proto.NoopAst.Expr.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = noop.model.proto.NoopAst.Expr.Type.BOOLEAN_LITERAL;
        return this;
      }
      
      // optional .BooleanLiteral booleanLiteral = 2;
      public boolean hasBooleanLiteral() {
        return result.hasBooleanLiteral();
      }
      public noop.model.proto.NoopAst.BooleanLiteral getBooleanLiteral() {
        return result.getBooleanLiteral();
      }
      public Builder setBooleanLiteral(noop.model.proto.NoopAst.BooleanLiteral value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBooleanLiteral = true;
        result.booleanLiteral_ = value;
        return this;
      }
      public Builder setBooleanLiteral(noop.model.proto.NoopAst.BooleanLiteral.Builder builderForValue) {
        result.hasBooleanLiteral = true;
        result.booleanLiteral_ = builderForValue.build();
        return this;
      }
      public Builder mergeBooleanLiteral(noop.model.proto.NoopAst.BooleanLiteral value) {
        if (result.hasBooleanLiteral() &&
            result.booleanLiteral_ != noop.model.proto.NoopAst.BooleanLiteral.getDefaultInstance()) {
          result.booleanLiteral_ =
            noop.model.proto.NoopAst.BooleanLiteral.newBuilder(result.booleanLiteral_).mergeFrom(value).buildPartial();
        } else {
          result.booleanLiteral_ = value;
        }
        result.hasBooleanLiteral = true;
        return this;
      }
      public Builder clearBooleanLiteral() {
        result.hasBooleanLiteral = false;
        result.booleanLiteral_ = noop.model.proto.NoopAst.BooleanLiteral.getDefaultInstance();
        return this;
      }
      
      // optional .StringLiteral stringLiteral = 3;
      public boolean hasStringLiteral() {
        return result.hasStringLiteral();
      }
      public noop.model.proto.NoopAst.StringLiteral getStringLiteral() {
        return result.getStringLiteral();
      }
      public Builder setStringLiteral(noop.model.proto.NoopAst.StringLiteral value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStringLiteral = true;
        result.stringLiteral_ = value;
        return this;
      }
      public Builder setStringLiteral(noop.model.proto.NoopAst.StringLiteral.Builder builderForValue) {
        result.hasStringLiteral = true;
        result.stringLiteral_ = builderForValue.build();
        return this;
      }
      public Builder mergeStringLiteral(noop.model.proto.NoopAst.StringLiteral value) {
        if (result.hasStringLiteral() &&
            result.stringLiteral_ != noop.model.proto.NoopAst.StringLiteral.getDefaultInstance()) {
          result.stringLiteral_ =
            noop.model.proto.NoopAst.StringLiteral.newBuilder(result.stringLiteral_).mergeFrom(value).buildPartial();
        } else {
          result.stringLiteral_ = value;
        }
        result.hasStringLiteral = true;
        return this;
      }
      public Builder clearStringLiteral() {
        result.hasStringLiteral = false;
        result.stringLiteral_ = noop.model.proto.NoopAst.StringLiteral.getDefaultInstance();
        return this;
      }
      
      // optional .IntLiteral intLiteral = 4;
      public boolean hasIntLiteral() {
        return result.hasIntLiteral();
      }
      public noop.model.proto.NoopAst.IntLiteral getIntLiteral() {
        return result.getIntLiteral();
      }
      public Builder setIntLiteral(noop.model.proto.NoopAst.IntLiteral value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasIntLiteral = true;
        result.intLiteral_ = value;
        return this;
      }
      public Builder setIntLiteral(noop.model.proto.NoopAst.IntLiteral.Builder builderForValue) {
        result.hasIntLiteral = true;
        result.intLiteral_ = builderForValue.build();
        return this;
      }
      public Builder mergeIntLiteral(noop.model.proto.NoopAst.IntLiteral value) {
        if (result.hasIntLiteral() &&
            result.intLiteral_ != noop.model.proto.NoopAst.IntLiteral.getDefaultInstance()) {
          result.intLiteral_ =
            noop.model.proto.NoopAst.IntLiteral.newBuilder(result.intLiteral_).mergeFrom(value).buildPartial();
        } else {
          result.intLiteral_ = value;
        }
        result.hasIntLiteral = true;
        return this;
      }
      public Builder clearIntLiteral() {
        result.hasIntLiteral = false;
        result.intLiteral_ = noop.model.proto.NoopAst.IntLiteral.getDefaultInstance();
        return this;
      }
    }
    
    static {
      noop.model.proto.NoopAst.getDescriptor();
    }
    
    static {
      noop.model.proto.NoopAst.internalForceInit();
    }
  }
  
  public static final class IntLiteral extends
      com.google.protobuf.GeneratedMessage {
    // Use IntLiteral.newBuilder() to construct.
    private IntLiteral() {}
    
    private static final IntLiteral defaultInstance = new IntLiteral();
    public static IntLiteral getDefaultInstance() {
      return defaultInstance;
    }
    
    public IntLiteral getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noop.model.proto.NoopAst.internal_static_IntLiteral_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noop.model.proto.NoopAst.internal_static_IntLiteral_fieldAccessorTable;
    }
    
    // required sint32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private int value_ = 0;
    public boolean hasValue() { return hasValue; }
    public int getValue() { return value_; }
    
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasValue()) {
        output.writeSInt32(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.IntLiteral parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(noop.model.proto.NoopAst.IntLiteral prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private noop.model.proto.NoopAst.IntLiteral result;
      
      // Construct using noop.model.proto.NoopAst.IntLiteral.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new noop.model.proto.NoopAst.IntLiteral();
        return builder;
      }
      
      protected noop.model.proto.NoopAst.IntLiteral internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new noop.model.proto.NoopAst.IntLiteral();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noop.model.proto.NoopAst.IntLiteral.getDescriptor();
      }
      
      public noop.model.proto.NoopAst.IntLiteral getDefaultInstanceForType() {
        return noop.model.proto.NoopAst.IntLiteral.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public noop.model.proto.NoopAst.IntLiteral build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private noop.model.proto.NoopAst.IntLiteral buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public noop.model.proto.NoopAst.IntLiteral buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        noop.model.proto.NoopAst.IntLiteral returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noop.model.proto.NoopAst.IntLiteral) {
          return mergeFrom((noop.model.proto.NoopAst.IntLiteral)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(noop.model.proto.NoopAst.IntLiteral other) {
        if (other == noop.model.proto.NoopAst.IntLiteral.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setValue(input.readSInt32());
              break;
            }
          }
        }
      }
      
      
      // required sint32 value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public int getValue() {
        return result.getValue();
      }
      public Builder setValue(int value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0;
        return this;
      }
    }
    
    static {
      noop.model.proto.NoopAst.getDescriptor();
    }
    
    static {
      noop.model.proto.NoopAst.internalForceInit();
    }
  }
  
  public static final class StringLiteral extends
      com.google.protobuf.GeneratedMessage {
    // Use StringLiteral.newBuilder() to construct.
    private StringLiteral() {}
    
    private static final StringLiteral defaultInstance = new StringLiteral();
    public static StringLiteral getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringLiteral getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noop.model.proto.NoopAst.internal_static_StringLiteral_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noop.model.proto.NoopAst.internal_static_StringLiteral_fieldAccessorTable;
    }
    
    // required string value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasValue()) {
        output.writeString(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.StringLiteral parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(noop.model.proto.NoopAst.StringLiteral prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private noop.model.proto.NoopAst.StringLiteral result;
      
      // Construct using noop.model.proto.NoopAst.StringLiteral.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new noop.model.proto.NoopAst.StringLiteral();
        return builder;
      }
      
      protected noop.model.proto.NoopAst.StringLiteral internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new noop.model.proto.NoopAst.StringLiteral();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noop.model.proto.NoopAst.StringLiteral.getDescriptor();
      }
      
      public noop.model.proto.NoopAst.StringLiteral getDefaultInstanceForType() {
        return noop.model.proto.NoopAst.StringLiteral.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public noop.model.proto.NoopAst.StringLiteral build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private noop.model.proto.NoopAst.StringLiteral buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public noop.model.proto.NoopAst.StringLiteral buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        noop.model.proto.NoopAst.StringLiteral returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noop.model.proto.NoopAst.StringLiteral) {
          return mergeFrom((noop.model.proto.NoopAst.StringLiteral)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(noop.model.proto.NoopAst.StringLiteral other) {
        if (other == noop.model.proto.NoopAst.StringLiteral.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
    }
    
    static {
      noop.model.proto.NoopAst.getDescriptor();
    }
    
    static {
      noop.model.proto.NoopAst.internalForceInit();
    }
  }
  
  public static final class BooleanLiteral extends
      com.google.protobuf.GeneratedMessage {
    // Use BooleanLiteral.newBuilder() to construct.
    private BooleanLiteral() {}
    
    private static final BooleanLiteral defaultInstance = new BooleanLiteral();
    public static BooleanLiteral getDefaultInstance() {
      return defaultInstance;
    }
    
    public BooleanLiteral getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noop.model.proto.NoopAst.internal_static_BooleanLiteral_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noop.model.proto.NoopAst.internal_static_BooleanLiteral_fieldAccessorTable;
    }
    
    // required bool value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private boolean value_ = false;
    public boolean hasValue() { return hasValue; }
    public boolean getValue() { return value_; }
    
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasValue()) {
        output.writeBool(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static noop.model.proto.NoopAst.BooleanLiteral parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(noop.model.proto.NoopAst.BooleanLiteral prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private noop.model.proto.NoopAst.BooleanLiteral result;
      
      // Construct using noop.model.proto.NoopAst.BooleanLiteral.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new noop.model.proto.NoopAst.BooleanLiteral();
        return builder;
      }
      
      protected noop.model.proto.NoopAst.BooleanLiteral internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new noop.model.proto.NoopAst.BooleanLiteral();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noop.model.proto.NoopAst.BooleanLiteral.getDescriptor();
      }
      
      public noop.model.proto.NoopAst.BooleanLiteral getDefaultInstanceForType() {
        return noop.model.proto.NoopAst.BooleanLiteral.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public noop.model.proto.NoopAst.BooleanLiteral build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private noop.model.proto.NoopAst.BooleanLiteral buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public noop.model.proto.NoopAst.BooleanLiteral buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        noop.model.proto.NoopAst.BooleanLiteral returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noop.model.proto.NoopAst.BooleanLiteral) {
          return mergeFrom((noop.model.proto.NoopAst.BooleanLiteral)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(noop.model.proto.NoopAst.BooleanLiteral other) {
        if (other == noop.model.proto.NoopAst.BooleanLiteral.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setValue(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required bool value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public boolean getValue() {
        return result.getValue();
      }
      public Builder setValue(boolean value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = false;
        return this;
      }
    }
    
    static {
      noop.model.proto.NoopAst.getDescriptor();
    }
    
    static {
      noop.model.proto.NoopAst.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Expr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Expr_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IntLiteral_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IntLiteral_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StringLiteral_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringLiteral_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BooleanLiteral_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BooleanLiteral_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"core/src/main/proto/noop_ast.proto\"\323\001\n" +
      "\004Expr\022\030\n\004type\030\001 \002(\0162\n.Expr.Type\022\'\n\016boole" +
      "anLiteral\030\002 \001(\0132\017.BooleanLiteral\022%\n\rstri" +
      "ngLiteral\030\003 \001(\0132\016.StringLiteral\022\037\n\nintLi" +
      "teral\030\004 \001(\0132\013.IntLiteral\"@\n\004Type\022\023\n\017BOOL" +
      "EAN_LITERAL\020\001\022\022\n\016STRING_LITERAL\020\002\022\017\n\013INT" +
      "_LITERAL\020\003\"\033\n\nIntLiteral\022\r\n\005value\030\001 \002(\021\"" +
      "\036\n\rStringLiteral\022\r\n\005value\030\001 \002(\t\"\037\n\016Boole" +
      "anLiteral\022\r\n\005value\030\001 \002(\010B\022\n\020noop.model.p" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Expr_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Expr_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Expr_descriptor,
              new java.lang.String[] { "Type", "BooleanLiteral", "StringLiteral", "IntLiteral", },
              noop.model.proto.NoopAst.Expr.class,
              noop.model.proto.NoopAst.Expr.Builder.class);
          internal_static_IntLiteral_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_IntLiteral_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IntLiteral_descriptor,
              new java.lang.String[] { "Value", },
              noop.model.proto.NoopAst.IntLiteral.class,
              noop.model.proto.NoopAst.IntLiteral.Builder.class);
          internal_static_StringLiteral_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_StringLiteral_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StringLiteral_descriptor,
              new java.lang.String[] { "Value", },
              noop.model.proto.NoopAst.StringLiteral.class,
              noop.model.proto.NoopAst.StringLiteral.Builder.class);
          internal_static_BooleanLiteral_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_BooleanLiteral_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BooleanLiteral_descriptor,
              new java.lang.String[] { "Value", },
              noop.model.proto.NoopAst.BooleanLiteral.class,
              noop.model.proto.NoopAst.BooleanLiteral.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
